### ISSUE TITLE
Support pages with similar names

### ISSUE THREAD

**Issue by Xiphe** [danielcondemarin/serverless-nextjs-plugin#67]
Given I have two nested pages
 - `pages/one/foo.js`
 - `pages/two/foo.js`

And I want to provide different [custom page routing](https://github.com/danielcondemarin/serverless-nextjs-plugin#custom-page-routing) configurations for these

Then I expect to write my custom pageConfig like this:

```yml
custom:
  serverless-nextjs:
    nextConfigDir: ./
    pageConfig:
      one/foo: #...
      two/foo: #...
```

But only the page file is used as a name, so I can not provide different configs for these.

I'd propose to use the relative page path as identifier in the custom config.

I'd be happy to provide a PR. But this change would be a braking change with the current API. Please let me know how to proceed.

**Comment by Xiphe** [comment]
Might also be fixed by new api proposed in https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/51

**Comment by danielcondemarin** [comment]
@Xiphe feel free to PR! This would be great. If there is any overlap with https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/51 we’ll sort it.

**Comment by Xiphe** [comment]
awesome! closing since https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/51 is released now

**Comment by danielcondemarin** [comment]
As an FYI - I'm still planning to support `pageConfig` which still doesn't use the new page identifiers `one/foo`, `two/foo` etc. That would be the breaking change which I'll do at some point later. For now the routes configuration covers most cases where you need custom `pageConfig`.

**Comment by Xiphe** [comment]
Ah, good to know. I'll see if the current change fixes the situation for me and might provide a PR if not. Thanks!
